FROM node:22.11.0-alpine AS base
WORKDIR /app

# Installation de PNPM
RUN npm i -g pnpm@9.15.2

# Copie des fichiers de dépendances
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

# Copie du code source
COPY . .

# Build de l'application
ARG POSTGRES_URL
ENV POSTGRES_URL=${POSTGRES_URL}


# Exposition du port et démarrage
EXPOSE 2000
CMD ["pnpm", "dev"]
