ARG PNPM_VERSION=9.15.2
FROM node:22.11.0-alpine AS base
WORKDIR /app

# Installation de PNPM
RUN npm i -g pnpm@${PNPM_VERSION}

# Copie des fichiers de dépendances
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

# Copie du code source
COPY . .

# Build de l'application
ARG POSTGRES_URL
ENV POSTGRES_URL=${POSTGRES_URL}
RUN pnpm run  build

# Exposition du port et démarrage
EXPOSE 3000
CMD ["pnpm", "start"]
